[test]
# Set default test timeout to 20 minutes (1200 seconds)
# PostgreSQL container startup can take 10-30 seconds
# Integration tests with multiple containers can take several minutes
timeout = 1200000

# Increase hook timeout to 60 seconds (default is 5 seconds)
# Needed for beforeAll hooks that create projects and wait for PostgreSQL
hookTimeout = 60000

# Tests run sequentially (not concurrent) to avoid:
# - State file locking contention (state.json)
# - ZFS dataset operation conflicts
# - Docker container memory pressure on small machines
# This is intentional for resource-intensive integration tests
