version: '3.8'

services:
  zfs-test:
    image: ubuntu:22.04
    container_name: betterpg-zfs-test
    privileged: true
    volumes:
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    command: sleep infinity
    environment:
      - DEBIAN_FRONTEND=noninteractive
