name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Install PostgreSQL client tools
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client jq

    - name: Install ZFS
      run: |
        sudo apt-get install -y zfsutils-linux

    - name: Create ZFS pool
      run: |
        # Create a file-based ZFS pool for testing (since we don't have real disks)
        sudo truncate -s 10G /tmp/zfs-pool.img
        sudo zpool create tank /tmp/zfs-pool.img
        sudo zpool status tank

    - name: Setup Docker permissions
      run: |
        # Ensure user can access Docker
        sudo usermod -aG docker $USER
        # Docker should already be running in GitHub Actions

    - name: Build pgd
      run: bun run build

    - name: Run V1 test suite
      run: |
        sudo -E bash scripts/test-v1.sh
      env:
        HOME: ${{ github.workspace }}

    - name: Run extended test suite
      run: |
        sudo -E bash scripts/extended-integration-test.sh
      env:
        HOME: ${{ github.workspace }}

    - name: Run advanced test suite
      run: |
        sudo -E bash scripts/test-advanced.sh
      env:
        HOME: ${{ github.workspace }}

    - name: Cleanup
      if: always()
      run: |
        # Clean up containers
        docker ps -a | grep pgd- | awk '{print $1}' | xargs -r docker rm -f 2>/dev/null || true
        # Clean up ZFS
        sudo zpool destroy tank 2>/dev/null || true
        sudo rm -f /tmp/zfs-pool.img
